##
# @author Alexander Breuer, Fabian Hofer, Vincent Gerlach (AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install valgrind
          sudo apt-get install cppcheck
          git submodule init
          git submodule update

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Sanitize
        run: |
          cmake --build build --config Debug --target sanitize_test
          ./build/sanitize_test
          cmake --build build --config Debug --target sanitize
          ./build/sanitize 25
          ./build/sanitize 25 25
          cmake --build build --config Release --target sanitize
          ./build/sanitize 500
          ./build/sanitize 50 50

      - name: Valgrind
        run: |
          cmake --build build --config Debug --target test
          valgrind build/test
          cmake --build build --config Debug --target simulation
          valgrind build/simulation 25
          valgrind build/simulation 25 25

      - name: Release
        run: |
          cmake --build build --config Release --target test
          ./build/test
          cmake --build build --config Release --target simulation
          ./build/simulation 500
          ./build/simulation 50 50

      - name: Arguments Test
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -D ENABLE_TESTMODE=ON ..
          cmake --build . --config Release --target simulation
          ./simulation 10
          ./simulation 10 10
          ./simulation 10 -B
          ./simulation 10 10 -B
          ./simulation 10 -s fwave
          ./simulation 10 10 -s fwave
          ./simulation 10 -s roe
          ./simulation 10 10 -s roe
          ./simulation 10 -s fwave -B
          ./simulation 10 10 -s fwave -B
          ./simulation 10 -r left -B
          ./simulation 10 10 -r left -B
          ./simulation 10 -r left right -s fwave
          ./simulation 10 10 -r left right -s fwave
          ./simulation 10 -r x -s roe
          ./simulation 10 10 -r x y -s roe
          ./simulation 10 -r all -s fwave -B
          ./simulation 10 10 -r all -s fwave -B
          ./simulation 10 -r left right top bottom -s fwave -B
          ./simulation 10 10 -r left right top bottom -s fwave -B
