name: Prebuild Docs

on:
  workflow_dispatch:
permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Requirements
        run: sudo apt-get install doxygen
          && pip3 install -r docs_sphinx/requirements.txt

      - name: Checkout repo
        uses: actions/checkout@v4.1.0

      - name: Build docs
        run: cd docs_sphinx
          && make clean
          && make html

      - name: Move Files
        run: cd docs_sphinx
          && rm -v -rf prebuild
          && mkdir -v prebuild
          && mv -v _build/html/* prebuild/

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: docs_sphinx/prebuild/**
          commit-msg: Update Prebuild Documentation
          github-token: ${{ secrets.PREBUILD_UPDATER }}
